### PR TITLE
Port ONNX to runtime

### PR DESCRIPTION
**Pull request by janniss91**
- Amend predict test
- Introduce ONNX model wipe endpoint

I've changed the code so that an ONNX runtime is used now.
There was no way described to do predictions with ONNX without saving these intermediate .onnx files.
Therefore, I created a new directory for them, which can be wiped thanks to a new endpoint.

I did not touch the train function yet since you said this would be done elsewhere in the future.

### CODE REVIEW

**Comment by ramonziai** [comment]
Thanks for the PR, I will look over it!

One minor thing: Any particular reason why 'requests' was removed from requirements.txt? I added that because otherwise the tests fail on GitHub Actions (see https://github.com/isaac-project/isaac-ml-service/pull/6/checks?check_run_id=945082658).

**Comment by janniss91** [comment]
Sorry, that must have happened accidentally when I put in the two new requirements.
I was already wondering why the tests fail.
I put requests back in, hopefully it works now.

**Comment by ramonziai** [comment]
Thanks, that particular problem is gone now. test_predict is still failing, it looks like the model file is not there, you might need to push it as well.

**Comment by janniss91** [comment]
The problem was that the ```onnx_models``` directory was not pushed to git because it is initially empty.
I added a .keep file to the directory to make git take it into account.

**Comment by janniss91** [comment]
1. The joblib dependency is removed now.
I was able to apply your suggestion to send meta data with the ONNX models (by means of metadata_props).
Also, I changed the behavior of the ```clf``` dictionary. It is not populated completely everytime that main.py is started.
Instead, ```clf``` is only populated with the model that is needed for prediction when the ```/predict``` endpoint is called or when a new model is trained. 
I think this change makes sense because prediction with ONNX runtime relies on file reading anyway. 
The ONNX model must (inconveniently) only be stored in ```clf``` to retrieve the output classes and columns.
Otherwise the ```clf``` dictionary could be removed completely.

2. As we discussed yesterday, I kept all parts that are responsible for training in the repo and also changed the code in the ```do_training``` function.

Tests: 
I removed the test that tested whether ```clf``` was empty because this is functionally checked when looking for the model ID in ```clf``` and the existence of a file with the corresponding model ID.

**Comment by ramonziai** [comment]
Thanks, changes are looking good! The only thing that remains from my perspective is where you say:

> Also, I changed the behavior of the clf dictionary. It is not populated completely everytime that main.py is started.
> Instead, clf is only populated with the model that is needed for prediction when the /predict endpoint is called or when a new > model is trained.
> I think this change makes sense because prediction with ONNX runtime relies on file reading anyway.
> The ONNX model must (inconveniently) only be stored in clf to retrieve the output classes and columns.
> Otherwise the clf dictionary could be removed completely.

The purpose of `clf` was to hold the models in memory so that they have to be read only once, because disk I/O and model deserialization/construction takes time, and should hence not be done for every predict request. I'd like to keep this feature if at all possible. Can you simply store `InferenceSession` objects instead of the sklearn classifiers we used to have?

**Comment by janniss91** [comment]
Ok I didn't know that it was important that all models need to be loaded in memory all the time.
I changed it back so that now model objects and inference session objects are loaded every time main.py is started.

**Comment by ramonziai** [comment]
Thanks! Actually it seems we do not need to hold both models _and_ InferenceSessions in memory. You can access the metadata you saved with the model through the `InferenceSession.get_modelmeta().custom_metadata_map` attribute. So keeping a dictionary of InferenceSessions around should be enough.

**Comment by janniss91** [comment]
Cool, thanks for looking that up!
There is only one dictionary with inference session objects left now.
The columns and output classes are retrieved from the inference session object directly.

**Comment by ramonziai** [comment]
Looks good! Just one oddity: in the 'output_classes' metadata attribute, I only see one class ('1') instead of two. Could you look into why this is the case?

**Comment by janniss91** [comment]
I don't know why it is one class only but it has been one class only since I started working with the repository if I remember correctly.
Are there supposed to be 2 classes?
I must admit I don't know how a Random Forest Classifier works exactly but I can read up on it.

**Comment by ramonziai** [comment]
There should be '0' for incorrect answers and '1' for correct ones, as it's a binary classification problem. Both have in the past been returned by the model.

**Comment by ramonziai** [comment]
Great analysis, thanks! Separating the testing procedure makes good sense to me. You could also make sure that the tests "clean up after themselves" so that there aren't any byproducts lying around.

> 2. There seems to be a problem with the model loading from the CAS string. When the tests are run, the default model is always created again on the basis of this CAS training. When training with it, only one output class is returned. Since I do not have insight into CAS object, I could not find out why.
>    I did comment out the test for train_with_CASes for now, though.

I'm guessing that's because one CAS only represents one classification instance, and a model trained from just this instance then only contains one class. So that's actually not a problem, because we'd never use such a model in practice anyway, it's only created for unit-testing purposes.

> 3. Would it be ok if I worked some time on clearly separating the testing procedure from the logic in main.py?
>    The fact that the testing procedure affects the default model and retrains it everytime the tests are run will be something that will fall on my feet again in the future, I'm quite sure. I think if I invest some time to have the tests operate on a model that is not in the main ONNX model directory, this could make things easier from now on, I guess. This way we could also take the hardcoded file name and `include` variable out of the main file.
>    Would that be ok?

Sounds good to me.

> EDIT
> I forgot: If you are wondering why the output_classes are not passed as metadata anymore.
> The predict_proba equivalent provides the output classes by default so this is not necessary anymore.

Nice, that means less manual coding in the metadata.

**Comment by janniss91** [comment]
Alright, I have separated the test procedure from the actual running of the service.

What changed?

1. /train is tested with a dataset with input data that I had created randomly.
This way we can test the endpoint without revealing real data to git.
There is a new subdirectory in the testdata directory that contains this new data.

2. The hard-coded filename was removed.
Instead I changed the /train endpoint from ```get``` to ```post``` method and introduced a pydantic model that demands the input of a filename.

3. Test changes:
- they do not affect the onnx-model directory anymore (exception: /predict ; see explanation in docstring of ```test_predict```)
- all tests actually work now, no tests are skipped anymore
- in some of the tests only the response status was checked, now outputs are checked as well

**Comment by janniss91** [comment]
The pydantic names have snake-cased names again.

**Comment by ramonziai** [comment]
Thanks! One little thing: it was "modelId" before, not "modelID". Could you adjust that?

**Comment by janniss91** [comment]
Sure, sorry I oversaw that.
This is fixed.

**Review by ramonziai — APPROVED** [review]

**Pull request merged**
