### PR TITLE
Predict from language data

### PR DESCRIPTION
**Pull request by janniss91**
**Please review on #9 and #10 before reviewing this branch.**
** It would also be good to merge master into this branch after #9  and #10 have been merged.**

There is a function called `predictFromAnswers` now. 
It takes a model_id  and predicts from the stored onnx model.

There is also a test for the function.

### CODE REVIEW

**Review by ramonziai — CHANGES_REQUESTED** [review]
Nicely done! The only thing I'm not completely sure about is the use of 'pickle' for serializing the BOW models to disk, because its very Python-specific and contrasts with the idea of portability offered by ONNX. Could you look into using something portable for serialization, e.g. JSON or protobuf?

**Comment by janniss91** [comment]
Yes, I'll see if I find a better solution for it.

**Comment by janniss91** [comment]
I have now decided to use json instead of pickle.
Maybe it's also an advantage that the serialized bag of words data is now human readable from the files.

Let me know if this is what you were looking for.

**Review by ramonziai — APPROVED** [review]

**Comment by ramonziai** [comment]
Thanks, yes I think having these models in human-readable form may prove useful for debugging and inspection.

**Pull request merged**
